name: Tests
on: [pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Test
        run: npm test
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout 🛎️
        uses: actions/checkout@v2.3.1
      - name: node
        uses: actions/setup-node@v3
        with:
          node-version: 18.4.0
      - name: deps
        run: npm install
      # Starship Infra setup
      # - Create a local kind cluster
      # - Creates a new namespace based on the name
      # - Spins up the infra with the given config file
      # - Waits till all nodes are running (timeout 30m)
      # - Port forward all ports to localhost for next steps to connect
      - name: infra
        id: starship-action
        uses: cosmology-tech/starship-action@0.2.15
        with:
          values: |
            chains:
              - name: osmosis-1
                type: osmosis
                numValidators: 1
                ports:
                  rest: 1313
                  rpc: 26653
                resources:
                  cpu: "0.2"
                  memory: "200M"

              - name: gaia-1
                type: cosmos
                numValidators: 1
                ports:
                  rest: 1317
                  rpc: 26657
                resources:
                  cpu: "0.2"
                  memory: "200M"

            relayers:
              - name: osmos-gaia
                type: hermes
                replicas: 1
                chains:
                  - osmosis-1
                  - gaia-1
                resources:
                  cpu: "0.1"
                  memory: "100M"

            explorer:
              enabled: false

            registry:
              enabled: true
              ports:
                rest: 8081
              resources:
                cpu: "0.1"
                memory: "100M"
