name: Tests
on: [pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Test
        run: npm test
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      # Starship Infra setup
      # - Create a local kind cluster
      # - Creates a new namespace based on the name
      # - Spins up the infra with the given config file
      # - Waits till all nodes are running (timeout 30m)
      # - Port forward all ports to localhost for next steps to connect
      # - name: infra
      #   id: starship-action
      #   uses: cosmology-tech/starship-action@0.2.15
      #   with:
      #     values: starship.yaml
      #     port-forward: true
      #     version: 0.1.38

      - name: setup
        run: npm run e2e:setup

      - name: start
        run: make start
        # run: helm repo update && helm search repo starship/devnet --version 0.1.38 && helm install -f starship.yaml skip-router starship/devnet --version 0.1.38 --wait && make port-forward

      - name: e2e
        run: npm run e2e:test
